16-clients
NovaDevelopersCo/NovaDev-Frontend pull request #20
Opened 2024-06-28 14:28 UTC by kowkaLYT

Completed all items ot task

2024-06-28 15:01 UTC, Zoomish reviewed
Отлично! Надо только чуть расширить ICustomer исходя из их модели. Модель можно найти по ссылке https://gitmind.com/app/docs/mo0z5dq8

2024-06-28 18:10 UTC, Zoomish requested changes
Нельзя зайти на странцу, так как не добавлен роут в main.tsx. А так же у клиента нет поля почта, но есть поле телефон

2024-06-28 19:21 UTC, kowkaLYT commented
![image](https://github.com/NovaDevelopersCo/NovaDev-Frontend/assets/153850235/c9ecbb9b-a5aa-4b73-84bf-681dec8dba28)
Роут добавила, а насчет телефона, там написана почта, если я правильно понимаю

2024-06-30 09:40 UTC, Zoomish requested changes
![image](https://github.com/NovaDevelopersCo/NovaDev-Frontend/assets/99123419/c68bea3f-4fc3-4694-9ad9-c01430000880)
Что это такое? Такого не должно быть!

2024-07-08 15:25 UTC, Kycedron requested changes
"ваш список клиентов" не реагирует на смену языка

2024-07-10 16:00 UTC, merged