feature/teams-page
NovaDevelopersCo/NovaDev-Frontend pull request #55
Opened 2024-08-22 13:23 UTC by kowkaLYT

2024-08-24 17:41 UTC, Zoomish requested changes
Много лишнего, не имеющее отношения к нашему проекту. Переписать названия импортов, перепроверить код, проверить страницы на работоспособность, так как на некоторых либо нет нужного либо они вообще не открываются

2024-08-24 17:41 UTC, Zoomish commented on src/pages/add-team/add-team.tsx
> +      rest_id: PathRest[values.restaurant],
Что за rest_id и level_access?

2024-08-24 17:41 UTC, Zoomish commented on src/utils/typesFromBackend.ts
>  export interface TAdvice {
Что такое TAdvice? Советы?

2024-08-31 19:00 UTC, kowkaLYT commented
Page "Team".  Create api for teams, clean code. Do nothing with page "Advices and tips" - task is postponed

2024-09-06 15:12 UTC, closed without merging